# Generated by Django 4.2.6 on 2023-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataProb',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('char', models.CharField(max_length=100, unique=True)),
                ('positive_prob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negative_prob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netural_prob', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
