# Generated by Django 4.2.6 on 2023-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_positive_freq', models.IntegerField(default=0)),
                ('total_negative_freq', models.IntegerField(default=0)),
                ('total_natural_freq', models.IntegerField(default=0)),
                ('total_freq', models.IntegerField(default=0)),
                ('total_positive_prob', models.FloatField(default=0.0)),
                ('total_negative_prob', models.FloatField(default=0.0)),
                ('total_natural_prob', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataprob',
            name='netural_prob',
        ),
        migrations.AddField(
            model_name='dataprob',
            name='natural_prob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dataprob',
            name='negative_prob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dataprob',
            name='positive_prob',
            field=models.FloatField(default=0.0),
        ),
    ]
